### ISSUE TITLE
Allow specifying expected output length when resampling

### ISSUE THREAD

**Issue by iver56** [adefossez/julius#13]
Hi Alexandre :)

Consider this scenario:

We have a machine learning model that takes in and outputs audio at a high sample rate. For some reasons (amongst other things execution time) the model uses an internal sample rate that is lower than the input-output. The output shape is expected to be the same as the input shape.

```
class ResampleWrapper(nn.Module):
    """
    This class downsamples audio before it's passed to the audio denoiser model,
    and upsamples the audio back to the original sample rate before returning.
    """

    def __init__(
        self,
        model: nn.Module,
        input_sample_rate: int = 48_000,
        internal_sample_rate: int = 32_000,
    ):
        super().__init__()
        self.model = model
        self.input_sample_rate = input_sample_rate
        self.internal_sample_rate = internal_sample_rate

        self.downsampler = ResampleFrac(
            self.input_sample_rate, self.internal_sample_rate
        )
        self.upsampler = ResampleFrac(self.internal_sample_rate, self.input_sample_rate)

    def forward(self, x):
        """
        :param x: tensor with shape (batch_size, num_channels, num_samples)
        :return: tensor with shape (batch_size, num_channels, num_samples)
        """
        x = self.downsampler(x)
        x = self.model(x)
        x = self.upsampler(x)
        return x
```

Depending on the exact length of the input, downsampling and then upsampling will often give an output that is off by one sample in length.

In `librosa` this kind of issue can be solved by setting the [fix parameter](https://librosa.org/doc/main/generated/librosa.resample.html) or by using [fix_length](https://librosa.org/doc/main/generated/librosa.util.fix_length.html#librosa.util.fix_length) manually.

I imagine that `julius.ResampleFrac` could provide a parameter called something like `expected_length` in its forward function that customizes the slice end offset in the end so that the result has the given length 😄

Would you like a pull request that adds this feature?

**Comment by adefossez** [comment]
Hey @iver56 , yes definitely length of the sequence can become problematic, especially with non trivial sample rates and when trying to align with other transforms.
I would be happy to accept a PR that allows to chose a custom length between `floor(length * new_sr / old_sr), ceil(length * new_sr / old_sr)`.
It might be as easy as changing this line https://github.com/adefossez/julius/blob/main/julius/resample.py#L122 but it is possible in some cases one need to do extra padding on the right too 3 lines above.

**Comment by iver56** [comment]
I believe an unintentional error was made - the allowed range of length is too strict now.

I wrote a test that fails in julius 0.2.5:

```
    def test_custom_output_length(self):
        x = th.ones(1, 230_001)
        downsampler = resample.ResampleFrac(old_sr=48_000, new_sr=36_000)
        upsampler = resample.ResampleFrac(old_sr=36_000, new_sr=48_000)

        downsampled_x = downsampler(x)
        upsampled_x = upsampler(downsampled_x, output_length=230_001)
        self.assertEqual(upsampled_x.shape, (1, 230_001))
```

```
======================================================================
ERROR: test_custom_output_length (tests.test_resample.TestResampleFrac)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\iver5\code\julius\tests\test_resample.py", line 143, in test_custom_output_length
    upsampled_x = upsampler(downsampled_x, output_length=230_001)
  File "C:\Users\iver5\Anaconda3\envs\julius\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\users\iver5\code\julius\julius\resample.py", line 143, in forward
    raise ValueError(f"output_length must be between 0 and {max_output_length}")
ValueError: output_length must be between 0 and 230000
```

Can we reopen this issue?

**Comment by iver56** [comment]
I found something that works for me in this specific use case - use `full=True` in the downsampler.

```
        downsampled_x = downsampler(x, full=True)
        upsampled_x = upsampler(downsampled_x, output_length=230_001)
```

**Comment by adefossez** [comment]
Oh in fact I think this is the expected behavior. You either need to pass `full=True` to the downsampler or compute yourself the length you should have for its output. But the default length will trim the last bits that is actually required by the upsampler just after. If this part is missing, the upsampler refuses to output the long output, which is expected.

When chaining multiple resampling, using `full=True` for all but the last one is the best way to ensure you can recover any output length. Let me know if you agree and I'll close back the issue.

**Comment by iver56** [comment]
Yeah, I agree, it's fine :) I was just confused initially. Maybe it's a good idea to add an example of this use case (downsample, do something, then upsample) to the documentation?
